apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deploymentdm2 
spec:
  replicas: 3 
  selector:
    matchLabels:
     app: my-nginx-pods
  template:
   metadata:
    labels:
     app: my-nginx-pods
   spec:
    containers:
    - name: my-nginx-container1
      image: nginx:1.7.9
      ports:
      - containerPort: 80
