apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment 
spec:
  replicas: 3 
  template:
   metadata:
    labels:
     app: my-nginx-pods
   spec:
    containers:
    - name: my-nginx-container1
      image: nginx:1.8
      ports:
      - containerPort: 80

