apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lable-difflabel
  labels:
    app: nginx-lblerr--difflabel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test-errdiff
  template:
    metadata:
      labels:
        app: nginx-test-err-difflabel
    spec:
      containers:
      - name: nginx-random-diff
        image: nginx:1.15.4
        ports:
        - containerPort: 80
