apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: my-nginx-pods
  type: LoadBalancer
  ports:
    - name: my-nginx-port
      port: 8080
      targetPort: 80

